# Generated by Django 3.0.8 on 2020-11-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_number',
            field=models.TextField(max_length=9, unique=True),
        ),
    ]
