# Generated by Django 3.0.8 on 2020-11-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='uncompleted_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
