# Generated by Django 3.0.8 on 2020-11-27 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201126_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.TextField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non Binary')]),
        ),
        migrations.AlterField(
            model_name='user_status',
            name='deliveries_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
