# Generated by Django 3.0.8 on 2020-11-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobberwork', '0002_auto_20201130_1245'),
        ('users', '0003_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='user_task',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to='jobberwork.NewTask'),
            preserve_default=False,
        ),
    ]
