# Generated by Django 3.0.8 on 2020-11-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobberwork', '0002_auto_20201130_1245'),
        ('users', '0005_auto_20201130_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='user_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='jobberwork.NewTask'),
        ),
    ]
