# Generated by Django 3.0.8 on 2020-11-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201130_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_status',
            name='average_review',
            field=models.IntegerField(default=0),
        ),
    ]
