# Generated by Django 3.0.8 on 2020-11-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_status_average_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_status',
            name='average_review',
            field=models.FloatField(default=0),
        ),
    ]
