# Generated by Django 3.0.8 on 2020-11-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobberwork', '0002_auto_20201125_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtask',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
